# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tip.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tipBox(object):
    def setupUi(self, tipBox):
        tipBox.setObjectName("tipBox")
        tipBox.resize(400, 300)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(tipBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(tipBox)
        QtCore.QMetaObject.connectSlotsByName(tipBox)

    def retranslateUi(self, tipBox):
        _translate = QtCore.QCoreApplication.translate
        tipBox.setWindowTitle(_translate("tipBox", "Справка"))
        self.plainTextEdit.setPlainText(_translate("tipBox", "Входные параметры:\n"
"* W - потребность;\n"
"* T - период расчетного времени;\n"
"* Cп - стоимость закупаемого продукта;\n"
"* Cx - расходы на хранение продукта;\n"
"* Cd - расходы на доставку продукта;\n"
"* Cy - потери, которое несет предприятие при дефиците ресурса;\n"
"* Δt - время доставки товара.\n"
"\n"
"Параметры скидки задаются с помощью нижнего и верхнего порога предоставления скидки. Верхний предел должен быть больше нижнего. Коэффициент скидки задается в процентах, значение не может быть более 100.\n"
"\n"
"Параметры исходных данных \n"
"Размер скидки\n"
"Выходные параметры:\n"
"* n -  количество поставок;\n"
"* K - коэффициент скидки;\n"
"* Q\' - размер заказа;\n"
"* M\' - максимальный размер запаса на складе;\n"
"* t\' - оптимальный интервал времени между двумя поставками;\n"
"* P - точка заказа;\n"
"* Sx - расходы на хранение;\n"
"* Sд - расходы на доставку;\n"
"* Sп - расходы на закупку;\n"
"* Sy - расходы вследствие дефицита;\n"
"* S - общие затраты.\n"
"\n"
"На графике красной пунктирной линией обозначен уровень точки заказа. График демонстрирует динамику изменения запасов ресурса. "))
